NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

users:
    type: rest
    resource: AppBundle\Controller\UserController

clients_individual:
    type: rest
    prefix: /clients
    resource: AppBundle\Controller\IndividualClientController

clients_legal: 
    type: rest
    prefix: /clients
    resource: AppBundle\Controller\LegalClientController
    
cases:
    type: rest
    resource: AppBundle\Controller\CasesController
    
calendars:
    type: rest
    resource: AppBundle\Controller\CalendarController