NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

register_user:
    path: /register
    defaults: { _controller: AppBundle:Register:register }
    methods: POST
    
confirm_user:
    path: /register/confirm/{token}
    defaults: { _controller: AppBundle:Register:confirm }
    methods: GET

users:
    type: rest
    resource: AppBundle\Controller\UserController

clients_individual:
    type: rest
    prefix: /clients
    resource: AppBundle\Controller\IndividualClientController

clients_legal: 
    type: rest
    prefix: /clients
    resource: AppBundle\Controller\LegalClientController
    
cases:
    type: rest
    resource: AppBundle\Controller\CasesController
    
documents:
    type: rest
    resource: AppBundle\Controller\DocumentsController
    
calendars:
    type: rest
    resource: AppBundle\Controller\CalendarController